Corrections for TF manifest
yandex-cloud-examples/yc-data-proc-clickhouse-data-exchange pull request #4
Opened 2024-12-09 10:33 UTC by mikhaildoc-documentat

2024-12-28 05:19 UTC, Odyvia42 requested changes

2024-12-28 05:19 UTC, Odyvia42 commented on data-proc-data-exchange-with-mch.tf
> +# Grant the service account storage.admin role to create storages and grant bucket ACLs
```suggestion
# Grant the service account storage.admin role to manage buckets and grant bucket ACLs
```

2024-12-28 05:19 UTC, Odyvia42 commented on data-proc-data-exchange-with-mch.tf
> +# Grant the service account storage.admin role to create storages and grant bucket ACLs
Предлагаю здесь поправить. 
Роль позволяет не только создавать, но и в целом управлять бакетом, в том числе и удалять его. Ну и термин "бакет" сюда больше подходит, чем хранилище.

2024-12-28 05:19 UTC, Odyvia42 commented on data-proc-data-exchange-with-mch.tf
>  resource "yandex_resourcemanager_folder_iam_binding" "s3-editor" {
```suggestion
resource "yandex_resourcemanager_folder_iam_binding" "s3-admin" {
```

2024-12-28 05:19 UTC, Odyvia42 commented on data-proc-data-exchange-with-mch.tf
> +    yandex_resourcemanager_folder_iam_binding.s3-editor
```suggestion
    yandex_resourcemanager_folder_iam_binding.s3-admin
```

2024-12-28 05:19 UTC, Odyvia42 commented on data-proc-data-exchange-with-mch.tf
> +    yandex_resourcemanager_folder_iam_binding.s3-editor
```suggestion
    yandex_resourcemanager_folder_iam_binding.s3-admin
```

2024-12-28 05:19 UTC, Odyvia42 commented on data-proc-data-exchange-with-mch.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Здесь было правильно. Давай вернём как было.

2024-12-28 05:22 UTC, Odyvia42 reviewed
Давай ещё добавим в кластер зависимости от ресурсов с ролями dataproc.agent и dataproc.provisioner, как в других манифестах.

2024-12-28 08:59 UTC, mikhaildoc-documentat commented on data-proc-data-exchange-with-mch.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Тут используется не явно прописанный путь, а локальная переменная, с ней путь нужно записывать именно так

2025-01-10 05:23 UTC, Odyvia42 approved these changes

2025-01-10 13:54 UTC, lanieuszko approved these changes

2025-01-10 13:54 UTC, merged